language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang

script: cmake . && make

addons:
  apt:
    packages:
    - libboost-system-dev
    - libboost-test-dev