language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang

before_script:
  - wget https://tls.mbed.org/download/mbedtls-2.6.0-gpl.tgz
  - tar -C external/lib60870/lib60870-C/dependencies/ -xvf mbedtls-2.6.0-gpl.tgz
  
script: cmake . && make && make test

addons:
  apt:
    packages:
    - libboost-system-dev
    - libboost-test-dev
    - libboost-date-time-dev
