#ifndef IEC104_104ENUMS_HPP_
#define IEC104_104ENUMS_HPP_

#include "core/namedenum.hpp"

namespace IEC104
{
    enum class DoublePoint
    {
        INTERMEDIATE = 0, // 0b00
        OFF          = 1, // 0b01
        ON           = 2, // 0b10
        FAULTY       = 3, // 0b11
    };
    using DoublePointEnum = NamedEnum<DoublePoint>;

    enum class ReasonCode
    {
        PERIODIC                      = 1,
        BACKGROUND_SCAN               = 2,
        SPONTANEOUS                   = 3,
        INITIALIZED                   = 4,
        REQUEST                       = 5,
                                     
        ACTIVATION                    = 6,
        CONFIRM_ACTIVATION            = 7,
        CANCEL_ACTIVATION             = 8,
        CONFIRM_CANCELLATION          = 9,
        FINISHED_ACTIVATION           = 10,
                                     
        RESPONSE_TO_REMOTE_CONTOL     = 11,
        RESPONSE_TO_LOCAL_CONTROL     = 12,
                                     
        FILE_TRANSFER                 = 13,
                                     
        RESERVED_CODE_14              = 14,
        RESERVED_CODE_15              = 15,
        RESERVED_CODE_16              = 16,
        RESERVED_CODE_17              = 17,
        RESERVED_CODE_18              = 18,
        RESERVED_CODE_19              = 19,
                                     
        GENERAL_INTERROGATION         = 20,
        GROUP_1_INTERROGATION         = 21,
        GROUP_2_INTERROGATION         = 22,
        GROUP_3_INTERROGATION         = 23,
        GROUP_4_INTERROGATION         = 24,
        GROUP_5_INTERROGATION         = 25,
        GROUP_6_INTERROGATION         = 26,
        GROUP_7_INTERROGATION         = 27,
        GROUP_8_INTERROGATION         = 28,
        GROUP_9_INTERROGATION         = 29,
        GROUP_10_INTERROGATION        = 30,
        GROUP_11_INTERROGATION        = 31,
        GROUP_12_INTERROGATION        = 32,
        GROUP_13_INTERROGATION        = 33,
        GROUP_14_INTERROGATION        = 34,
        GROUP_15_INTERROGATION        = 35,
        GROUP_16_INTERROGATION        = 36,

        COUNTER_INTERROGATION         = 37,
        COUNTER_GROUP_1_INTERROGATION = 38,
        COUNTER_GROUP_2_INTERROGATION = 39,
        COUNTER_GROUP_3_INTERROGATION = 40,
        COUNTER_GROUP_4_INTERROGATION = 41,

        RESERVED_CODE_42              = 42,
        RESERVED_CODE_43              = 43,

        UNKNOWN_TYPE_ID               = 44,
        UNKNOWN_REASON                = 45,
        UNKNOWN_COMMON_ADDRESS        = 46,
        UNKNOWN_INFO_ADDRESS          = 47,

        CUSTOM_CODE_48                = 48,
        CUSTOM_CODE_49                = 49,
        CUSTOM_CODE_50                = 50,
        CUSTOM_CODE_51                = 51,
        CUSTOM_CODE_52                = 52,
        CUSTOM_CODE_53                = 53,
        CUSTOM_CODE_54                = 54,
        CUSTOM_CODE_55                = 55,
        CUSTOM_CODE_56                = 56,
        CUSTOM_CODE_57                = 57,
        CUSTOM_CODE_58                = 58,
        CUSTOM_CODE_59                = 59,
        CUSTOM_CODE_60                = 60,
        CUSTOM_CODE_61                = 61,
        CUSTOM_CODE_62                = 62,
        CUSTOM_CODE_63                = 63,
    } ;
    using ReasonCodeEnum = NamedEnum<ReasonCode>;

    enum Type
    {
        // Process information - monitoring direction
        M_SP_NA_1 = 1,
        M_SP_TA_1 = 2,
        M_DP_NA_1 = 3,
        M_DP_TA_1 = 4,
        M_ST_NA_1 = 5,
        M_ST_TA_1 = 6,
        M_BO_NA_1 = 7,
        M_BO_TA_1 = 8,
        M_ME_NA_1 = 9,
        M_ME_TA_1 = 10,
        M_ME_NB_1 = 11,
        M_ME_TB_1 = 12,
        M_ME_NC_1 = 13,
        M_ME_TC_1 = 14,
        M_IT_NA_1 = 15,
        M_IT_TA_1 = 16,
        M_EP_TA_1 = 17,
        M_EP_TB_1 = 18,
        M_EP_TC_1 = 19,
        M_PS_NA_1 = 20,
        M_ME_ND_1 = 21,

        M_SP_TB_1 = 30,
        M_DP_TB_1 = 31, // e.g. switching device position with timestamp
        M_ST_TB_1 = 32,
        M_BO_TB_1 = 33,
        M_ME_TD_1 = 34,
        M_ME_TE_1 = 35,
        M_ME_TF_1 = 36,
        M_IT_TB_1 = 37,
        M_EP_TD_1 = 38,
        M_EP_TE_1 = 39,
        M_EP_TF_1 = 40,

        // Process information - control direction
        C_SC_NA_1 = 45,
        C_DC_NA_1 = 46, // e.g. switching device command
        C_RC_NA_1 = 47,
        C_SE_NA_1 = 48,
        C_SE_NB_1 = 49,
        C_SE_NC_1 = 50,
        C_BO_NA_1 = 51,

        // System information - monitoring direction
        M_EI_NA_1 = 70, // Station initialization finished

        // System information - control direction
        C_IC_NA_1 = 100, // general interrogation
        C_CI_NA_1 = 101,
        C_RQ_NA_1 = 102,
        C_CS_NA_1 = 103,
        C_TS_NA_1 = 104,
        C_RP_NA_1 = 105,
        C_CD_NA_1 = 106,

        // Parameters - control direction
        P_ME_NA_1 = 110,
        P_ME_NB_1 = 111,
        P_ME_NC_1 = 112,
        P_AC_NA_1 = 113,

        // File transfer
        F_FR_NA_1 = 120,
        F_SR_NA_1 = 121,
        F_SC_NA_1 = 122,
        F_LS_NA_1 = 123,
        F_AF_NA_1 = 124,
        F_SG_NA_1 = 125,
        F_DR_TA_1 = 126
    };
    using TypeEnum = NamedEnum<Type>;


    enum class InterrogationQualifier
    {
        UNUSED = 0,

        RESERVED_CODE_1  = 1,
        RESERVED_CODE_2  = 2,
        RESERVED_CODE_3  = 3,
        RESERVED_CODE_4  = 4,
        RESERVED_CODE_5  = 5,
        RESERVED_CODE_6  = 6,
        RESERVED_CODE_7  = 7,
        RESERVED_CODE_8  = 8,
        RESERVED_CODE_9  = 9,
        RESERVED_CODE_10 = 10,
        RESERVED_CODE_11 = 11,
        RESERVED_CODE_12 = 12,
        RESERVED_CODE_13 = 13,
        RESERVED_CODE_14 = 14,
        RESERVED_CODE_15 = 15,
        RESERVED_CODE_16 = 16,
        RESERVED_CODE_17 = 17,
        RESERVED_CODE_18 = 18,
        RESERVED_CODE_19 = 19,

        INTERROGATE_STATION  = 20,

        INTERROGATE_GROUP_1  = 21,
        INTERROGATE_GROUP_2  = 22,
        INTERROGATE_GROUP_3  = 23,
        INTERROGATE_GROUP_4  = 24,
        INTERROGATE_GROUP_5  = 25,
        INTERROGATE_GROUP_6  = 26,
        INTERROGATE_GROUP_7  = 27,
        INTERROGATE_GROUP_8  = 28,
        INTERROGATE_GROUP_9  = 29,
        INTERROGATE_GROUP_10 = 30,
        INTERROGATE_GROUP_11 = 31,
        INTERROGATE_GROUP_12 = 32,
        INTERROGATE_GROUP_13 = 33,
        INTERROGATE_GROUP_14 = 34,
        INTERROGATE_GROUP_15 = 35,
        INTERROGATE_GROUP_16 = 36,

        RESERVED_CODE_37,
        RESERVED_CODE_38,
        RESERVED_CODE_39,
        RESERVED_CODE_40,
        RESERVED_CODE_41,
        RESERVED_CODE_42,
        RESERVED_CODE_43,
        RESERVED_CODE_44,
        RESERVED_CODE_45,
        RESERVED_CODE_46,
        RESERVED_CODE_47,
        RESERVED_CODE_48,
        RESERVED_CODE_49,
        RESERVED_CODE_50,
        RESERVED_CODE_51,
        RESERVED_CODE_52,
        RESERVED_CODE_53,
        RESERVED_CODE_54,
        RESERVED_CODE_55,
        RESERVED_CODE_56,
        RESERVED_CODE_57,
        RESERVED_CODE_58,
        RESERVED_CODE_59,
        RESERVED_CODE_60,
        RESERVED_CODE_61,
        RESERVED_CODE_62,
        RESERVED_CODE_63,

        CUSTOM_CODE_64,
        CUSTOM_CODE_65,
        CUSTOM_CODE_66,
        CUSTOM_CODE_67,
        CUSTOM_CODE_68,
        CUSTOM_CODE_69,
        CUSTOM_CODE_70,
        CUSTOM_CODE_71,
        CUSTOM_CODE_72,
        CUSTOM_CODE_73,
        CUSTOM_CODE_74,
        CUSTOM_CODE_75,
        CUSTOM_CODE_76,
        CUSTOM_CODE_77,
        CUSTOM_CODE_78,
        CUSTOM_CODE_79,
        CUSTOM_CODE_80,
        CUSTOM_CODE_81,
        CUSTOM_CODE_82,
        CUSTOM_CODE_83,
        CUSTOM_CODE_84,
        CUSTOM_CODE_85,
        CUSTOM_CODE_86,
        CUSTOM_CODE_87,
        CUSTOM_CODE_88,
        CUSTOM_CODE_89,
        CUSTOM_CODE_90,
        CUSTOM_CODE_91,
        CUSTOM_CODE_92,
        CUSTOM_CODE_93,
        CUSTOM_CODE_94,
        CUSTOM_CODE_95,
        CUSTOM_CODE_96,
        CUSTOM_CODE_97,
        CUSTOM_CODE_98,
        CUSTOM_CODE_99,
        CUSTOM_CODE_100,
        CUSTOM_CODE_101,
        CUSTOM_CODE_102,
        CUSTOM_CODE_103,
        CUSTOM_CODE_104,
        CUSTOM_CODE_105,
        CUSTOM_CODE_106,
        CUSTOM_CODE_107,
        CUSTOM_CODE_108,
        CUSTOM_CODE_109,
        CUSTOM_CODE_110,
        CUSTOM_CODE_111,
        CUSTOM_CODE_112,
        CUSTOM_CODE_113,
        CUSTOM_CODE_114,
        CUSTOM_CODE_115,
        CUSTOM_CODE_116,
        CUSTOM_CODE_117,
        CUSTOM_CODE_118,
        CUSTOM_CODE_119,
        CUSTOM_CODE_120,
        CUSTOM_CODE_121,
        CUSTOM_CODE_122,
        CUSTOM_CODE_123,
        CUSTOM_CODE_124,
        CUSTOM_CODE_125,
        CUSTOM_CODE_126,
        CUSTOM_CODE_127,
        CUSTOM_CODE_128,
        CUSTOM_CODE_129,
        CUSTOM_CODE_130,
        CUSTOM_CODE_131,
        CUSTOM_CODE_132,
        CUSTOM_CODE_133,
        CUSTOM_CODE_134,
        CUSTOM_CODE_135,
        CUSTOM_CODE_136,
        CUSTOM_CODE_137,
        CUSTOM_CODE_138,
        CUSTOM_CODE_139,
        CUSTOM_CODE_140,
        CUSTOM_CODE_141,
        CUSTOM_CODE_142,
        CUSTOM_CODE_143,
        CUSTOM_CODE_144,
        CUSTOM_CODE_145,
        CUSTOM_CODE_146,
        CUSTOM_CODE_147,
        CUSTOM_CODE_148,
        CUSTOM_CODE_149,
        CUSTOM_CODE_150,
        CUSTOM_CODE_151,
        CUSTOM_CODE_152,
        CUSTOM_CODE_153,
        CUSTOM_CODE_154,
        CUSTOM_CODE_155,
        CUSTOM_CODE_156,
        CUSTOM_CODE_157,
        CUSTOM_CODE_158,
        CUSTOM_CODE_159,
        CUSTOM_CODE_160,
        CUSTOM_CODE_161,
        CUSTOM_CODE_162,
        CUSTOM_CODE_163,
        CUSTOM_CODE_164,
        CUSTOM_CODE_165,
        CUSTOM_CODE_166,
        CUSTOM_CODE_167,
        CUSTOM_CODE_168,
        CUSTOM_CODE_169,
        CUSTOM_CODE_170,
        CUSTOM_CODE_171,
        CUSTOM_CODE_172,
        CUSTOM_CODE_173,
        CUSTOM_CODE_174,
        CUSTOM_CODE_175,
        CUSTOM_CODE_176,
        CUSTOM_CODE_177,
        CUSTOM_CODE_178,
        CUSTOM_CODE_179,
        CUSTOM_CODE_180,
        CUSTOM_CODE_181,
        CUSTOM_CODE_182,
        CUSTOM_CODE_183,
        CUSTOM_CODE_184,
        CUSTOM_CODE_185,
        CUSTOM_CODE_186,
        CUSTOM_CODE_187,
        CUSTOM_CODE_188,
        CUSTOM_CODE_189,
        CUSTOM_CODE_190,
        CUSTOM_CODE_191,
        CUSTOM_CODE_192,
        CUSTOM_CODE_193,
        CUSTOM_CODE_194,
        CUSTOM_CODE_195,
        CUSTOM_CODE_196,
        CUSTOM_CODE_197,
        CUSTOM_CODE_198,
        CUSTOM_CODE_199,
        CUSTOM_CODE_200,
        CUSTOM_CODE_201,
        CUSTOM_CODE_202,
        CUSTOM_CODE_203,
        CUSTOM_CODE_204,
        CUSTOM_CODE_205,
        CUSTOM_CODE_206,
        CUSTOM_CODE_207,
        CUSTOM_CODE_208,
        CUSTOM_CODE_209,
        CUSTOM_CODE_210,
        CUSTOM_CODE_211,
        CUSTOM_CODE_212,
        CUSTOM_CODE_213,
        CUSTOM_CODE_214,
        CUSTOM_CODE_215,
        CUSTOM_CODE_216,
        CUSTOM_CODE_217,
        CUSTOM_CODE_218,
        CUSTOM_CODE_219,
        CUSTOM_CODE_220,
        CUSTOM_CODE_221,
        CUSTOM_CODE_222,
        CUSTOM_CODE_223,
        CUSTOM_CODE_224,
        CUSTOM_CODE_225,
        CUSTOM_CODE_226,
        CUSTOM_CODE_227,
        CUSTOM_CODE_228,
        CUSTOM_CODE_229,
        CUSTOM_CODE_230,
        CUSTOM_CODE_231,
        CUSTOM_CODE_232,
        CUSTOM_CODE_233,
        CUSTOM_CODE_234,
        CUSTOM_CODE_235,
        CUSTOM_CODE_236,
        CUSTOM_CODE_237,
        CUSTOM_CODE_238,
        CUSTOM_CODE_239,
        CUSTOM_CODE_240,
        CUSTOM_CODE_241,
        CUSTOM_CODE_242,
        CUSTOM_CODE_243,
        CUSTOM_CODE_244,
        CUSTOM_CODE_245,
        CUSTOM_CODE_246,
        CUSTOM_CODE_247,
        CUSTOM_CODE_248,
        CUSTOM_CODE_249,
        CUSTOM_CODE_250,
        CUSTOM_CODE_251,
        CUSTOM_CODE_252,
        CUSTOM_CODE_253,
        CUSTOM_CODE_254,
        CUSTOM_CODE_255,
    };
    using InterrogationQualifierEnum = NamedEnum<InterrogationQualifier>;
}

#endif
