#include "protocols/iec104/104enums.hpp"

template <>
IEC104::DoublePointEnum::DefinitionContainer IEC104::DoublePointEnum::msDefinition = {
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::INTERMEDIATE, "intermediate"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::OFF,          "off"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::ON,           "on"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::FAULTY,       "faulty")
};

template <>
IEC104::ReasonCodeEnum::DefinitionContainer IEC104::ReasonCodeEnum::msDefinition = {
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::PERIODIC                      ,"periodic"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::BACKGROUND_SCAN               ,"background scan"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::SPONTANEOUS                   ,"spontaneous"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::INITIALIZED                   ,"initialized"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::REQUEST                       ,"request"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::ACTIVATION                    ,"activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CONFIRM_ACTIVATION            ,"confirm activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CANCEL_ACTIVATION             ,"cancel activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CONFIRM_CANCELLATION          ,"confirm cancellation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::FINISHED_ACTIVATION           ,"finished activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESPONSE_TO_REMOTE_CONTOL     ,"response to remote control"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESPONSE_TO_LOCAL_CONTROL     ,"response to local control"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::FILE_TRANSFER                 ,"file transfer"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_14              ,"reserved 14"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_15              ,"reserved 15"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_16              ,"reserved 16"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_17              ,"reserved 17"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_18              ,"reserved 18"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_19              ,"reserved 19"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GENERAL_INTERROGATION         ,"general interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_1_INTERROGATION         ,"group 1 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_2_INTERROGATION         ,"group 2 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_3_INTERROGATION         ,"group 3 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_4_INTERROGATION         ,"group 4 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_5_INTERROGATION         ,"group 5 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_6_INTERROGATION         ,"group 6 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_7_INTERROGATION         ,"group 7 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_8_INTERROGATION         ,"group 8 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_9_INTERROGATION         ,"group 9 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_10_INTERROGATION        ,"group 10 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_11_INTERROGATION        ,"group 11 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_12_INTERROGATION        ,"group 12 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_13_INTERROGATION        ,"group 13 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_14_INTERROGATION        ,"group 14 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_15_INTERROGATION        ,"group 15 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_16_INTERROGATION        ,"group 16 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_INTERROGATION         ,"counter interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_1_INTERROGATION ,"counter group 1 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_2_INTERROGATION ,"counter group 2 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_3_INTERROGATION ,"counter group 3 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_4_INTERROGATION ,"counter group 4 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_42              ,"reserved 42"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_43              ,"reserved 43"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_TYPE_ID               ,"unknown type id"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_REASON                ,"unknown reason"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_COMMON_ADDRESS        ,"unknown common address"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_INFO_ADDRESS          ,"unknown info address"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_48                ,"custom reason 48"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_49                ,"custom reason 49"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_50                ,"custom reason 50"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_51                ,"custom reason 51"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_52                ,"custom reason 52"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_53                ,"custom reason 53"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_54                ,"custom reason 54"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_55                ,"custom reason 55"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_56                ,"custom reason 56"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_57                ,"custom reason 57"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_58                ,"custom reason 58"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_59                ,"custom reason 59"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_60                ,"custom reason 60"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_61                ,"custom reason 61"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_62                ,"custom reason 62"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_63                ,"custom reason 63")
};

template<>
IEC104::TypeEnum::DefinitionContainer IEC104::TypeEnum::msDefinition = {
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_NA_1, "M_SP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_TA_1, "M_SP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_NA_1, "M_DP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_TA_1, "M_DP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_NA_1, "M_ST_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_TA_1, "M_ST_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_NA_1, "M_BO_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_TA_1, "M_BO_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NA_1, "M_ME_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TA_1, "M_ME_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NB_1, "M_ME_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TB_1, "M_ME_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NC_1, "M_ME_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TC_1, "M_ME_TC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_NA_1, "M_IT_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_TA_1, "M_IT_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TA_1, "M_EP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TB_1, "M_EP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TC_1, "M_EP_TC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_PS_NA_1, "M_PS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_ND_1, "M_ME_ND_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_TB_1, "M_SP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_TB_1, "M_DP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_TB_1, "M_ST_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_TB_1, "M_BO_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TD_1, "M_ME_TD_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TE_1, "M_ME_TE_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TF_1, "M_ME_TF_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_TB_1, "M_IT_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TD_1, "M_EP_TD_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TE_1, "M_EP_TE_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TF_1, "M_EP_TF_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SC_NA_1, "C_SC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_DC_NA_1, "C_DC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RC_NA_1, "C_RC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NA_1, "C_SE_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NB_1, "C_SE_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NC_1, "C_SE_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_BO_NA_1, "C_BO_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EI_NA_1, "M_EI_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_IC_NA_1, "C_IC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CI_NA_1, "C_CI_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RQ_NA_1, "C_RQ_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CS_NA_1, "C_CS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_TS_NA_1, "C_TS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RP_NA_1, "C_RP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CD_NA_1, "C_CD_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NA_1, "P_ME_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NB_1, "P_ME_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NC_1, "P_ME_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_AC_NA_1, "P_AC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_FR_NA_1, "F_FR_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SR_NA_1, "F_SR_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SC_NA_1, "F_SC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_LS_NA_1, "F_LS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_AF_NA_1, "F_AF_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SG_NA_1, "F_SG_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_DR_TA_1, "F_DR_TA_1")
};

