#include "protocols/iec104/104enums.hpp"

template <>
IEC104::DoublePointEnum::DefinitionContainer IEC104::DoublePointEnum::msDefinition = {
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::INTERMEDIATE, "intermediate"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::OFF,          "off"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::ON,           "on"),
        IEC104::DoublePointEnum::Definition(IEC104::DoublePoint::FAULTY,       "faulty")
};

template <>
IEC104::ReasonCodeEnum::DefinitionContainer IEC104::ReasonCodeEnum::msDefinition = {
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::PERIODIC                      ,"periodic"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::BACKGROUND_SCAN               ,"background scan"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::SPONTANEOUS                   ,"spontaneous"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::INITIALIZED                   ,"initialized"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::REQUEST                       ,"request"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::ACTIVATION                    ,"activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CONFIRM_ACTIVATION            ,"confirm activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CANCEL_ACTIVATION             ,"cancel activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CONFIRM_CANCELLATION          ,"confirm cancellation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::FINISHED_ACTIVATION           ,"finished activation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESPONSE_TO_REMOTE_CONTOL     ,"response to remote control"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESPONSE_TO_LOCAL_CONTROL     ,"response to local control"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::FILE_TRANSFER                 ,"file transfer"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_14              ,"reserved 14"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_15              ,"reserved 15"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_16              ,"reserved 16"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_17              ,"reserved 17"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_18              ,"reserved 18"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_19              ,"reserved 19"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GENERAL_INTERROGATION         ,"general interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_1_INTERROGATION         ,"group 1 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_2_INTERROGATION         ,"group 2 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_3_INTERROGATION         ,"group 3 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_4_INTERROGATION         ,"group 4 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_5_INTERROGATION         ,"group 5 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_6_INTERROGATION         ,"group 6 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_7_INTERROGATION         ,"group 7 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_8_INTERROGATION         ,"group 8 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_9_INTERROGATION         ,"group 9 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_10_INTERROGATION        ,"group 10 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_11_INTERROGATION        ,"group 11 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_12_INTERROGATION        ,"group 12 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_13_INTERROGATION        ,"group 13 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_14_INTERROGATION        ,"group 14 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_15_INTERROGATION        ,"group 15 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::GROUP_16_INTERROGATION        ,"group 16 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_INTERROGATION         ,"counter interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_1_INTERROGATION ,"counter group 1 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_2_INTERROGATION ,"counter group 2 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_3_INTERROGATION ,"counter group 3 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::COUNTER_GROUP_4_INTERROGATION ,"counter group 4 interrogation"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_42              ,"reserved 42"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::RESERVED_CODE_43              ,"reserved 43"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_TYPE_ID               ,"unknown type id"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_REASON                ,"unknown reason"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_COMMON_ADDRESS        ,"unknown common address"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::UNKNOWN_INFO_ADDRESS          ,"unknown info address"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_48                ,"custom reason 48"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_49                ,"custom reason 49"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_50                ,"custom reason 50"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_51                ,"custom reason 51"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_52                ,"custom reason 52"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_53                ,"custom reason 53"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_54                ,"custom reason 54"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_55                ,"custom reason 55"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_56                ,"custom reason 56"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_57                ,"custom reason 57"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_58                ,"custom reason 58"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_59                ,"custom reason 59"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_60                ,"custom reason 60"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_61                ,"custom reason 61"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_62                ,"custom reason 62"),
        IEC104::ReasonCodeEnum::Definition(IEC104::ReasonCode::CUSTOM_CODE_63                ,"custom reason 63")
};

template<>
IEC104::TypeEnum::DefinitionContainer IEC104::TypeEnum::msDefinition = {
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_NA_1, "M_SP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_TA_1, "M_SP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_NA_1, "M_DP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_TA_1, "M_DP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_NA_1, "M_ST_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_TA_1, "M_ST_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_NA_1, "M_BO_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_TA_1, "M_BO_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NA_1, "M_ME_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TA_1, "M_ME_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NB_1, "M_ME_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TB_1, "M_ME_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_NC_1, "M_ME_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TC_1, "M_ME_TC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_NA_1, "M_IT_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_TA_1, "M_IT_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TA_1, "M_EP_TA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TB_1, "M_EP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TC_1, "M_EP_TC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_PS_NA_1, "M_PS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_ND_1, "M_ME_ND_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_SP_TB_1, "M_SP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_DP_TB_1, "M_DP_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ST_TB_1, "M_ST_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_BO_TB_1, "M_BO_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TD_1, "M_ME_TD_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TE_1, "M_ME_TE_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_ME_TF_1, "M_ME_TF_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_IT_TB_1, "M_IT_TB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TD_1, "M_EP_TD_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TE_1, "M_EP_TE_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EP_TF_1, "M_EP_TF_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SC_NA_1, "C_SC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_DC_NA_1, "C_DC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RC_NA_1, "C_RC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NA_1, "C_SE_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NB_1, "C_SE_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_SE_NC_1, "C_SE_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_BO_NA_1, "C_BO_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::M_EI_NA_1, "M_EI_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_IC_NA_1, "C_IC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CI_NA_1, "C_CI_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RQ_NA_1, "C_RQ_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CS_NA_1, "C_CS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_TS_NA_1, "C_TS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_RP_NA_1, "C_RP_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::C_CD_NA_1, "C_CD_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NA_1, "P_ME_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NB_1, "P_ME_NB_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_ME_NC_1, "P_ME_NC_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::P_AC_NA_1, "P_AC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_FR_NA_1, "F_FR_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SR_NA_1, "F_SR_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SC_NA_1, "F_SC_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_LS_NA_1, "F_LS_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_AF_NA_1, "F_AF_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_SG_NA_1, "F_SG_NA_1"),
    IEC104::TypeEnum::Definition(IEC104::Type::F_DR_TA_1, "F_DR_TA_1")
};


template<>
IEC104::InterrogationQualifierEnum::DefinitionContainer IEC104::InterrogationQualifierEnum::msDefinition = {
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::UNUSED,               "unused"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_1,      "reserved code 1"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_2,      "reserved code 2"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_3,      "reserved code 3"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_4,      "reserved code 4"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_5,      "reserved code 5"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_6,      "reserved code 6"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_7,      "reserved code 7"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_8,      "reserved code 8"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_9,      "reserved code 9"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_10,     "reserved code 10"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_11,     "reserved code 11"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_12,     "reserved code 12"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_13,     "reserved code 13"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_14,     "reserved code 14"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_15,     "reserved code 15"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_16,     "reserved code 16"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_17,     "reserved code 17"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_18,     "reserved code 18"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_19,     "reserved code 19"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_STATION,  "interrogate station"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_1,  "interrogate group 1"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_2,  "interrogate group 2"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_3,  "interrogate group 3"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_4,  "interrogate group 4"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_5,  "interrogate group 5"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_6,  "interrogate group 6"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_7,  "interrogate group 7"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_8,  "interrogate group 8"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_9,  "interrogate group 9"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_10, "interrogate group 10"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_11, "interrogate group 11"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_12, "interrogate group 12"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_13, "interrogate group 13"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_14, "interrogate group 14"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_15, "interrogate group 15"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::INTERROGATE_GROUP_16, "interrogate group 16"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_37,     "reserved code 37"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_38,     "reserved code 38"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_39,     "reserved code 39"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_40,     "reserved code 40"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_41,     "reserved code 41"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_42,     "reserved code 42"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_43,     "reserved code 43"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_44,     "reserved code 44"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_45,     "reserved code 45"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_46,     "reserved code 46"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_47,     "reserved code 47"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_48,     "reserved code 48"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_49,     "reserved code 49"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_50,     "reserved code 50"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_51,     "reserved code 51"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_52,     "reserved code 52"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_53,     "reserved code 53"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_54,     "reserved code 54"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_55,     "reserved code 55"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_56,     "reserved code 56"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_57,     "reserved code 57"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_58,     "reserved code 58"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_59,     "reserved code 59"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_60,     "reserved code 60"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_61,     "reserved code 61"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_62,     "reserved code 62"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::RESERVED_CODE_63,     "reserved code 63"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_64,       "custom code 64"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_65,       "custom code 65"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_66,       "custom code 66"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_67,       "custom code 67"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_68,       "custom code 68"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_69,       "custom code 69"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_70,       "custom code 70"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_71,       "custom code 71"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_72,       "custom code 72"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_73,       "custom code 73"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_74,       "custom code 74"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_75,       "custom code 75"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_76,       "custom code 76"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_77,       "custom code 77"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_78,       "custom code 78"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_79,       "custom code 79"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_80,       "custom code 80"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_81,       "custom code 81"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_82,       "custom code 82"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_83,       "custom code 83"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_84,       "custom code 84"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_85,       "custom code 85"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_86,       "custom code 86"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_87,       "custom code 87"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_88,       "custom code 88"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_89,       "custom code 89"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_90,       "custom code 90"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_91,       "custom code 91"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_92,       "custom code 92"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_93,       "custom code 93"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_94,       "custom code 94"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_95,       "custom code 95"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_96,       "custom code 96"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_97,       "custom code 97"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_98,       "custom code 98"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_99,       "custom code 99"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_100,      "custom code 100"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_101,      "custom code 101"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_102,      "custom code 102"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_103,      "custom code 103"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_104,      "custom code 104"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_105,      "custom code 105"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_106,      "custom code 106"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_107,      "custom code 107"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_108,      "custom code 108"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_109,      "custom code 109"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_110,      "custom code 110"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_111,      "custom code 111"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_112,      "custom code 112"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_113,      "custom code 113"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_114,      "custom code 114"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_115,      "custom code 115"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_116,      "custom code 116"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_117,      "custom code 117"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_118,      "custom code 118"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_119,      "custom code 119"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_120,      "custom code 120"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_121,      "custom code 121"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_122,      "custom code 122"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_123,      "custom code 123"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_124,      "custom code 124"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_125,      "custom code 125"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_126,      "custom code 126"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_127,      "custom code 127"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_128,      "custom code 128"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_129,      "custom code 129"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_130,      "custom code 130"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_131,      "custom code 131"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_132,      "custom code 132"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_133,      "custom code 133"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_134,      "custom code 134"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_135,      "custom code 135"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_136,      "custom code 136"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_137,      "custom code 137"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_138,      "custom code 138"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_139,      "custom code 139"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_140,      "custom code 140"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_141,      "custom code 141"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_142,      "custom code 142"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_143,      "custom code 143"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_144,      "custom code 144"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_145,      "custom code 145"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_146,      "custom code 146"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_147,      "custom code 147"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_148,      "custom code 148"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_149,      "custom code 149"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_150,      "custom code 150"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_151,      "custom code 151"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_152,      "custom code 152"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_153,      "custom code 153"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_154,      "custom code 154"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_155,      "custom code 155"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_156,      "custom code 156"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_157,      "custom code 157"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_158,      "custom code 158"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_159,      "custom code 159"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_160,      "custom code 160"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_161,      "custom code 161"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_162,      "custom code 162"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_163,      "custom code 163"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_164,      "custom code 164"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_165,      "custom code 165"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_166,      "custom code 166"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_167,      "custom code 167"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_168,      "custom code 168"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_169,      "custom code 169"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_170,      "custom code 170"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_171,      "custom code 171"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_172,      "custom code 172"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_173,      "custom code 173"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_174,      "custom code 174"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_175,      "custom code 175"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_176,      "custom code 176"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_177,      "custom code 177"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_178,      "custom code 178"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_179,      "custom code 179"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_180,      "custom code 180"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_181,      "custom code 181"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_182,      "custom code 182"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_183,      "custom code 183"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_184,      "custom code 184"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_185,      "custom code 185"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_186,      "custom code 186"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_187,      "custom code 187"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_188,      "custom code 188"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_189,      "custom code 189"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_190,      "custom code 190"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_191,      "custom code 191"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_192,      "custom code 192"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_193,      "custom code 193"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_194,      "custom code 194"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_195,      "custom code 195"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_196,      "custom code 196"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_197,      "custom code 197"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_198,      "custom code 198"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_199,      "custom code 199"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_200,      "custom code 200"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_201,      "custom code 201"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_202,      "custom code 202"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_203,      "custom code 203"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_204,      "custom code 204"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_205,      "custom code 205"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_206,      "custom code 206"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_207,      "custom code 207"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_208,      "custom code 208"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_209,      "custom code 209"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_210,      "custom code 210"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_211,      "custom code 211"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_212,      "custom code 212"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_213,      "custom code 213"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_214,      "custom code 214"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_215,      "custom code 215"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_216,      "custom code 216"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_217,      "custom code 217"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_218,      "custom code 218"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_219,      "custom code 219"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_220,      "custom code 220"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_221,      "custom code 221"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_222,      "custom code 222"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_223,      "custom code 223"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_224,      "custom code 224"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_225,      "custom code 225"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_226,      "custom code 226"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_227,      "custom code 227"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_228,      "custom code 228"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_229,      "custom code 229"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_230,      "custom code 230"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_231,      "custom code 231"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_232,      "custom code 232"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_233,      "custom code 233"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_234,      "custom code 234"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_235,      "custom code 235"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_236,      "custom code 236"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_237,      "custom code 237"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_238,      "custom code 238"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_239,      "custom code 239"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_240,      "custom code 240"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_241,      "custom code 241"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_242,      "custom code 242"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_243,      "custom code 243"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_244,      "custom code 244"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_245,      "custom code 245"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_246,      "custom code 246"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_247,      "custom code 247"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_248,      "custom code 248"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_249,      "custom code 249"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_250,      "custom code 250"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_251,      "custom code 251"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_252,      "custom code 252"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_253,      "custom code 253"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_254,      "custom code 254"),
    IEC104::InterrogationQualifierEnum::Definition(IEC104::InterrogationQualifier::CUSTOM_CODE_255,      "custom code 255")
};